# Generated by Django 3.0.7 on 2023-06-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
