# Generated by Django 3.0.7 on 2023-06-23 02:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_auto_20230623_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='music_sound',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('musik_3_personel', 'Musik 3 Personel'), ('musik_4_personel', 'Musik 4 Personel'), ('sound_system_1000_watt', 'Sound System 1000 Watt'), ('sound_system_3000_watt', 'Sound System 3000 Watt')], max_length=79),
        ),
    ]
