# Generated by Django 3.0.7 on 2023-06-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_auto_20230625_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='is_available',
            new_name='is_featured',
        ),
    ]
