# Generated by Django 3.0.7 on 2023-07-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_auto_20230625_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='is_featured',
            new_name='Unggulan',
        ),
    ]
