# Generated by Django 3.0.7 on 2023-07-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_auto_20230710_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wedding',
            old_name='price',
            new_name='Harga',
        ),
        migrations.RenameField(
            model_name='wedding',
            old_name='Wedding_title',
            new_name='Paket',
        ),
    ]
